/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

import controladores.EncriptadorAES;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import controladores.crudController;
import interfazGrafica.CapturaHuella;
import java.awt.Font;
import java.io.UnsupportedEncodingException;
import java.security.InvalidKeyException;
import java.security.NoSuchAlgorithmException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.crypto.BadPaddingException;
import javax.crypto.IllegalBlockSizeException;
import javax.crypto.NoSuchPaddingException;
import javax.sound.midi.ControllerEventListener;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.JTableHeader;

/**
 *
 * @author Tefy
 */
public class crudAdmin extends javax.swing.JPanel {

    private boolean actualizarGuardar;

    /**
     * Creates new form crud
     */
    public crudAdmin() {
        initComponents();

        DefaultTableModel modeloTabla = new DefaultTableModel();
        jtblCrud.setRowHeight(30);
        if (!new crudController().existeUsuarioSinHuella(jtxtCedula.getText(), "usuarios")) {
            new crudController().eliminarDatosIncompletos();
        }
        jtblCrud.setModel(new crudController().cargarTablaUser());
        formatoTitulos();
        jlblOcultar.setVisible(false);
        this.bloquearTextosyBusqueda();
        jtblCrud.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent lse) {
                bloquearTextosyBusqueda();
                if (jtblCrud.getSelectedRow() != -1) {
                    Integer fila = jtblCrud.getSelectedRow();
                    String[] datos = new crudController().buscarCedula(jtblCrud.getValueAt(fila, 1).toString());
                    jtxtCedula.setText(datos[0]);
                    jtxtNombre.setText(datos[1]);
                    jtxtApellido.setText(datos[2]);
                    jtxtTelefono.setText(datos[3]);
                    jtxtDireccion.setText(datos[4]);
                    jtxtUsuario.setText(datos[5]);
                    try {
                        //jpassClave.setText(datos[6]);
                        jpassClave.setText(new EncriptadorAES().desencriptar(datos[6], "SisTech"));
                    } catch (UnsupportedEncodingException ex) {
                        Logger.getLogger(crudAdmin.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (NoSuchAlgorithmException ex) {
                        Logger.getLogger(crudAdmin.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (InvalidKeyException ex) {
                        Logger.getLogger(crudAdmin.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (NoSuchPaddingException ex) {
                        Logger.getLogger(crudAdmin.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (IllegalBlockSizeException ex) {
                        Logger.getLogger(crudAdmin.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (BadPaddingException ex) {
                        Logger.getLogger(crudAdmin.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    if (datos[7].equals("1")) {
                        jchkAdmin.setSelected(true);
                        jchkSecre.setSelected(false);
                    } else {
                        jchkAdmin.setSelected(false);
                        jchkSecre.setSelected(true);
                    }
                }
            }

        });
    }

    public void formatoTitulos() {
        JTableHeader th;
        th = jtblCrud.getTableHeader();
        Font fuente = new Font("Microsoft Yahei", Font.BOLD, 14);
        th.setFont(fuente);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tipoUsuario = new javax.swing.ButtonGroup();
        jpCrud = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jlNombre = new javax.swing.JLabel();
        jlApellido = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtxtNombre = new javax.swing.JTextField();
        jtxtApellido = new javax.swing.JTextField();
        jtxtCedula = new javax.swing.JTextField();
        jchkAdmin = new javax.swing.JCheckBox();
        jbtnGuardar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jbtnActualizar = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jtxtTelefono = new javax.swing.JTextField();
        jtxtDireccion = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jtxtUsuario = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jchkSecre = new javax.swing.JCheckBox();
        jLabel25 = new javax.swing.JLabel();
        jbtnCancelar = new javax.swing.JButton();
        jbtnHuella = new javax.swing.JButton();
        jlblVer = new javax.swing.JLabel();
        jlblOcultar = new javax.swing.JLabel();
        jpassClave = new javax.swing.JPasswordField();
        jpPanelOpciones = new javax.swing.JPanel();
        jpAniadir = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jpEliminar = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jpActualizar = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblCrud = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jtxtBusqueda = new javax.swing.JTextField();

        jpCrud.setBackground(new java.awt.Color(255, 255, 255));
        jpCrud.setPreferredSize(new java.awt.Dimension(1250, 590));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlNombre.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jlNombre.setText("Nombre");
        jPanel2.add(jlNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 86, -1, -1));

        jlApellido.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jlApellido.setText("Apellido");
        jPanel2.add(jlApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 133, -1, -1));

        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jLabel3.setText("Cédula");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 46, -1, -1));

        jLabel4.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jLabel4.setText("Contraseña");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 316, -1, -1));

        jLabel5.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jLabel5.setText("Tipo usuario");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 356, -1, -1));

        jtxtNombre.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 16)); // NOI18N
        jtxtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtNombreKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtNombreKeyTyped(evt);
            }
        });
        jPanel2.add(jtxtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 86, 173, -1));

        jtxtApellido.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 16)); // NOI18N
        jtxtApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtApellidoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtApellidoKeyTyped(evt);
            }
        });
        jPanel2.add(jtxtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 132, 173, -1));

        jtxtCedula.setFont(new java.awt.Font("Microsoft JhengHei", 0, 16)); // NOI18N
        jtxtCedula.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxtCedulaFocusLost(evt);
            }
        });
        jtxtCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtCedulaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtCedulaKeyTyped(evt);
            }
        });
        jPanel2.add(jtxtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 44, 173, -1));

        jchkAdmin.setBackground(new java.awt.Color(204, 204, 204));
        tipoUsuario.add(jchkAdmin);
        jchkAdmin.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 13)); // NOI18N
        jchkAdmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jchkAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 356, 28, -1));

        jbtnGuardar.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 13)); // NOI18N
        jbtnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesFrames/floppy-disk.png"))); // NOI18N
        jbtnGuardar.setText("Guardar");
        jbtnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGuardarActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, 119, -1));

        jLabel6.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        jLabel6.setText("Datos Personales");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 13, -1, -1));

        jbtnActualizar.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 13)); // NOI18N
        jbtnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesFrames/updateUser.png"))); // NOI18N
        jbtnActualizar.setText("Actualizar");
        jbtnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnActualizarActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 500, -1, -1));

        jLabel13.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jLabel13.setText("Telefono");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 175, -1, -1));

        jtxtTelefono.setFont(new java.awt.Font("Microsoft JhengHei", 0, 16)); // NOI18N
        jtxtTelefono.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxtTelefonoFocusLost(evt);
            }
        });
        jtxtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtTelefonoKeyTyped(evt);
            }
        });
        jPanel2.add(jtxtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 173, 173, -1));

        jtxtDireccion.setFont(new java.awt.Font("Microsoft JhengHei", 0, 16)); // NOI18N
        jtxtDireccion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxtDireccionFocusLost(evt);
            }
        });
        jtxtDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtDireccionKeyTyped(evt);
            }
        });
        jPanel2.add(jtxtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 220, 173, -1));

        jLabel14.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jLabel14.setText("Direccion");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 222, -1, -1));

        jtxtUsuario.setFont(new java.awt.Font("Microsoft JhengHei", 0, 16)); // NOI18N
        jtxtUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxtUsuarioFocusLost(evt);
            }
        });
        jtxtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtUsuarioKeyTyped(evt);
            }
        });
        jPanel2.add(jtxtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 267, 173, -1));

        jLabel23.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jLabel23.setText("Usuario");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 269, -1, -1));

        jLabel24.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jLabel24.setText("Administrador/a");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 357, -1, -1));

        jchkSecre.setBackground(new java.awt.Color(204, 204, 204));
        tipoUsuario.add(jchkSecre);
        jchkSecre.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 13)); // NOI18N
        jchkSecre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jchkSecre, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 394, -1, -1));

        jLabel25.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jLabel25.setText("Secretario/a");
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 394, -1, -1));

        jbtnCancelar.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 13)); // NOI18N
        jbtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesFrames/cancel.png"))); // NOI18N
        jbtnCancelar.setText("Cancelar");
        jbtnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 540, 119, -1));

        jbtnHuella.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 13)); // NOI18N
        jbtnHuella.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesFrames/huellaIcon.png"))); // NOI18N
        jbtnHuella.setText("Registrar huella dactilar");
        jbtnHuella.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnHuella.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnHuellaActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnHuella, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 258, -1));

        jlblVer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesFrames/view.png"))); // NOI18N
        jlblVer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlblVerMouseClicked(evt);
            }
        });
        jPanel2.add(jlblVer, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, -1, -1));
        jlblVer.getAccessibleContext().setAccessibleParent(this);

        jlblOcultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesFrames/hide.png"))); // NOI18N
        jlblOcultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlblOcultarMouseClicked(evt);
            }
        });
        jPanel2.add(jlblOcultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 315, 30, 30));
        jPanel2.add(jpassClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 160, 30));

        jpPanelOpciones.setBackground(new java.awt.Color(204, 204, 204));

        jpAniadir.setBackground(new java.awt.Color(204, 204, 204));
        jpAniadir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpAniadir.setPreferredSize(new java.awt.Dimension(105, 105));
        jpAniadir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpAniadirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpAniadirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpAniadirMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jpAniadirMousePressed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesFrames/agregar.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jLabel2.setText("Añadir");

        javax.swing.GroupLayout jpAniadirLayout = new javax.swing.GroupLayout(jpAniadir);
        jpAniadir.setLayout(jpAniadirLayout);
        jpAniadirLayout.setHorizontalGroup(
            jpAniadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpAniadirLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jpAniadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(23, 23, 23))
        );
        jpAniadirLayout.setVerticalGroup(
            jpAniadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAniadirLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpEliminar.setBackground(new java.awt.Color(204, 204, 204));
        jpEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpEliminar.setPreferredSize(new java.awt.Dimension(105, 105));
        jpEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpEliminarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpEliminarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpEliminarMouseExited(evt);
            }
        });

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesFrames/eliminar.png"))); // NOI18N
        jLabel8.setPreferredSize(new java.awt.Dimension(105, 105));

        jLabel9.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Eliminar");

        javax.swing.GroupLayout jpEliminarLayout = new javax.swing.GroupLayout(jpEliminar);
        jpEliminar.setLayout(jpEliminarLayout);
        jpEliminarLayout.setHorizontalGroup(
            jpEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpEliminarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addContainerGap())
            .addGroup(jpEliminarLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpEliminarLayout.setVerticalGroup(
            jpEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEliminarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addContainerGap())
        );

        jpActualizar.setBackground(new java.awt.Color(204, 204, 204));
        jpActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpActualizar.setPreferredSize(new java.awt.Dimension(105, 105));
        jpActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpActualizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpActualizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpActualizarMouseExited(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesFrames/hacia-adelante.png"))); // NOI18N

        jLabel11.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Actualizar");

        javax.swing.GroupLayout jpActualizarLayout = new javax.swing.GroupLayout(jpActualizar);
        jpActualizar.setLayout(jpActualizarLayout);
        jpActualizarLayout.setHorizontalGroup(
            jpActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpActualizarLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jpActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpActualizarLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpActualizarLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addContainerGap())))
        );
        jpActualizarLayout.setVerticalGroup(
            jpActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpActualizarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addContainerGap())
        );

        javax.swing.GroupLayout jpPanelOpcionesLayout = new javax.swing.GroupLayout(jpPanelOpciones);
        jpPanelOpciones.setLayout(jpPanelOpcionesLayout);
        jpPanelOpcionesLayout.setHorizontalGroup(
            jpPanelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPanelOpcionesLayout.createSequentialGroup()
                .addContainerGap(286, Short.MAX_VALUE)
                .addComponent(jpAniadir, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(283, 283, 283))
        );
        jpPanelOpcionesLayout.setVerticalGroup(
            jpPanelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
            .addComponent(jpEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
            .addComponent(jpAniadir, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        jScrollPane1.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        jtblCrud.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        jtblCrud.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtblCrud);

        jLabel12.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jLabel12.setText("Buscar por cédula: ");

        jtxtBusqueda.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jtxtBusqueda.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxtBusquedaFocusLost(evt);
            }
        });
        jtxtBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtBusquedaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtBusquedaKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jtxtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jpCrudLayout = new javax.swing.GroupLayout(jpCrud);
        jpCrud.setLayout(jpCrudLayout);
        jpCrudLayout.setHorizontalGroup(
            jpCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCrudLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpPanelOpciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        jpCrudLayout.setVerticalGroup(
            jpCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpCrudLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jpCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpCrudLayout.createSequentialGroup()
                        .addComponent(jpPanelOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(188, 188, 188))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jpCrud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jpCrud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jpAniadirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpAniadirMouseEntered
        jpAniadir.setBackground(Color.white);
    }//GEN-LAST:event_jpAniadirMouseEntered

    private void jpAniadirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpAniadirMouseExited
        jpAniadir.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_jpAniadirMouseExited

    private void jpAniadirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpAniadirMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpAniadirMousePressed

    private void jpAniadirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpAniadirMouseClicked
//              jpAniadir.setBackground(Color.white);
        this.actualizarGuardar = true;
        this.limpiarTextos();
        this.desbloquearTextos();
        this.jbtnGuardar.setEnabled(true);
        this.jbtnCancelar.setEnabled(true);
        this.jbtnHuella.setEnabled(true);
        this.jchkAdmin.setSelected(false);
        this.jchkSecre.setSelected(false);
    }//GEN-LAST:event_jpAniadirMouseClicked

    private void jpActualizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpActualizarMouseEntered
        jpActualizar.setBackground(Color.white);
    }//GEN-LAST:event_jpActualizarMouseEntered

    private void jpActualizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpActualizarMouseExited
        jpActualizar.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_jpActualizarMouseExited

    private void jbtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGuardarActionPerformed
        if (!formularioCompleto()) {
            if (new crudController().existeUsuario(jtxtCedula.getText(), "usuarios")) {
                if (new crudController().existeUsuario(jtxtCedula.getText(), jtxtNombre.getText(), jtxtApellido.getText())) {
                    JOptionPane.showMessageDialog(this, "El usuario con C.I. " + jtxtCedula.getText() + " ya esta registrado");
                } else {
                    String[] datosUser = new String[8];
                    datosUser[0] = jtxtCedula.getText();
                    datosUser[1] = jtxtUsuario.getText();
                    try {
                        //datosUser[2] = new String(jpassClave.getPassword());
                        datosUser[2] = new EncriptadorAES().encriptar(new String(jpassClave.getPassword()), "SisTech");
                    } catch (UnsupportedEncodingException ex) {
                        Logger.getLogger(crudAdmin.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (NoSuchAlgorithmException ex) {
                        Logger.getLogger(crudAdmin.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (InvalidKeyException ex) {
                        Logger.getLogger(crudAdmin.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (NoSuchPaddingException ex) {
                        Logger.getLogger(crudAdmin.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (IllegalBlockSizeException ex) {
                        Logger.getLogger(crudAdmin.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (BadPaddingException ex) {
                        Logger.getLogger(crudAdmin.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    datosUser[3] = jtxtNombre.getText();
                    datosUser[4] = jtxtApellido.getText();
                    datosUser[5] = jtxtTelefono.getText();
                    datosUser[6] = jtxtDireccion.getText();
                    String checkSeleccion;
                    if (jchkAdmin.isSelected()) {
                        checkSeleccion = "1";
                    } else {
                        checkSeleccion = "0";
                    }
                    datosUser[7] = checkSeleccion;
                    new crudController().agregarUsuario(datosUser);
                    this.limpiarTextos();
                    this.bloquearTextosyBusqueda();
                }
                jtblCrud.setModel(new crudController().cargarTablaUser());
            } else {
                JOptionPane.showMessageDialog(this, "Registre la huella antes de guardar el usuario");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Complete el formulario antes de guardar");
        }
    }//GEN-LAST:event_jbtnGuardarActionPerformed

    private void jpActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpActualizarMouseClicked
        if (jtxtCedula.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Primero seleccione una fila de la tabla");
        } else {
            this.actualizarGuardar = false;
            this.desbloquearTextosActualizar();
            jbtnHuella.setEnabled(true);
            this.jbtnGuardar.setEnabled(false);
            jbtnActualizar.setEnabled(true);
            jbtnCancelar.setEnabled(true);
        }
    }//GEN-LAST:event_jpActualizarMouseClicked

    private void jtxtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtNombreKeyTyped
        int key = evt.getKeyChar();

        boolean mayusculas = key >= 65 && key <= 90;
        boolean minusculas = key >= 97 && key <= 122;
        boolean espacio = key == 32;

        if (!(minusculas || mayusculas || espacio)) {
            evt.consume();
        }
        if (jtxtNombre.getText().length() > 40) {
            evt.consume();
        }
    }//GEN-LAST:event_jtxtNombreKeyTyped

    private void jtxtApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtApellidoKeyTyped
        int key = evt.getKeyChar();

        boolean mayusculas = key >= 65 && key <= 90;
        boolean minusculas = key >= 97 && key <= 122;
//        boolean tildes = key <= 160 && key <= 163;
//        boolean tildes2 = key == 130;
        boolean espacio = key == 32;
//        boolean acento = key == 239;
//        boolean enie = key ==164 && key ==165; 

        if (jtxtApellido.getText().length() > 40) {
            evt.consume();
        }
    }//GEN-LAST:event_jtxtApellidoKeyTyped

    private void jtxtCedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtCedulaKeyTyped
        int key = evt.getKeyChar();

        boolean numeros = key >= 48 && key <= 57;

        if (!numeros) {
            evt.consume();
        }
        if (jtxtCedula.getText().length() >= 10) {
            evt.consume();
        }
    }//GEN-LAST:event_jtxtCedulaKeyTyped

    private void jtxtBusquedaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtBusquedaKeyTyped
        int key = evt.getKeyChar();

        boolean numeros = key >= 48 && key <= 57;

        if (!numeros) {
            evt.consume();
        }
    }//GEN-LAST:event_jtxtBusquedaKeyTyped

    private void jtxtBusquedaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtBusquedaFocusLost

    }//GEN-LAST:event_jtxtBusquedaFocusLost

    private void jtxtCedulaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtCedulaFocusLost
        if (jtxtCedula.isEnabled()) {
            if (!this.validadorDeCedula(jtxtCedula.getText())) {
                JOptionPane.showMessageDialog(null, "La cédula ingresada no es válida");
                jtxtCedula.setText("");
            }
        }
    }//GEN-LAST:event_jtxtCedulaFocusLost

    private void jbtnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnActualizarActionPerformed
        if (!formularioCompleto()) {
            String[] datosUser = new String[8];
            datosUser[0] = jtxtCedula.getText();
            datosUser[1] = jtxtUsuario.getText();
            try {
                //datosUser[2] = new String(jpassClave.getPassword());
                datosUser[2] = new EncriptadorAES().encriptar(new String(jpassClave.getPassword()), "SisTech");
            } catch (UnsupportedEncodingException ex) {
                Logger.getLogger(crudAdmin.class.getName()).log(Level.SEVERE, null, ex);
            } catch (NoSuchAlgorithmException ex) {
                Logger.getLogger(crudAdmin.class.getName()).log(Level.SEVERE, null, ex);
            } catch (InvalidKeyException ex) {
                Logger.getLogger(crudAdmin.class.getName()).log(Level.SEVERE, null, ex);
            } catch (NoSuchPaddingException ex) {
                Logger.getLogger(crudAdmin.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IllegalBlockSizeException ex) {
                Logger.getLogger(crudAdmin.class.getName()).log(Level.SEVERE, null, ex);
            } catch (BadPaddingException ex) {
                Logger.getLogger(crudAdmin.class.getName()).log(Level.SEVERE, null, ex);
            }
            datosUser[3] = jtxtNombre.getText();
            datosUser[4] = jtxtApellido.getText();
            datosUser[5] = jtxtTelefono.getText();
            datosUser[6] = jtxtDireccion.getText();
            String checkSeleccion;
            if (jchkAdmin.isSelected()) {
                checkSeleccion = "1";
            } else {
                checkSeleccion = "0";
            }
            datosUser[7] = checkSeleccion;
            new crudController().actualizarUsuario(datosUser);
            this.limpiarTextos();
            this.bloquearTextosyBusqueda();
        } else {
            JOptionPane.showMessageDialog(this, "Complete el formulario antes de actualizar");
        }
        jtblCrud.setModel(new crudController().cargarTablaUser());
    }//GEN-LAST:event_jbtnActualizarActionPerformed

    private void jpEliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpEliminarMouseExited
        jpEliminar.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_jpEliminarMouseExited

    private void jpEliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpEliminarMouseEntered
        jpEliminar.setBackground(Color.WHITE);
    }//GEN-LAST:event_jpEliminarMouseEntered

    private void jpEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpEliminarMouseClicked
        if (jtxtCedula.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Primero seleccione una fila de la tabla");
        } else {
            String mensaje = String.format("%s\n\n%15s%-20s\n%15s%s %s\n%15s%-20s\n%15s%-20s",
                    "¿Esta seguro de eliminar usuario?", "Cedula: ", jtxtCedula.getText(),
                    "Nombre: ", jtxtNombre.getText(), jtxtApellido.getText(),
                    "Telefono: ", jtxtTelefono.getText(),
                    "Direccion: ", jtxtDireccion.getText());
            int opcion = JOptionPane.showConfirmDialog(this, mensaje, "Eliminar Estudiate", JOptionPane.WARNING_MESSAGE, JOptionPane.YES_NO_OPTION);
            if (opcion == 0) {
                new crudController().removerUsuario(jtxtCedula.getText());
                limpiarTextos();
                bloquearTextosyBusqueda();
            }
            jtblCrud.setModel(new crudController().cargarTablaUser());
        }
    }//GEN-LAST:event_jpEliminarMouseClicked

    private void jtxtTelefonoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtTelefonoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTelefonoFocusLost

    private void jtxtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtTelefonoKeyTyped
        int key = evt.getKeyChar();

        boolean numeros = key >= 48 && key <= 57;

        if (!numeros) {
            evt.consume();
        }
        if (jtxtTelefono.getText().length() >= 10) {
            evt.consume();
        }
    }//GEN-LAST:event_jtxtTelefonoKeyTyped

    private void jtxtDireccionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtDireccionFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtDireccionFocusLost

    private void jtxtDireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtDireccionKeyTyped
        int key = evt.getKeyChar();

        boolean mayusculas = key >= 65 && key <= 90;
        boolean minusculas = key >= 97 && key <= 122;
        boolean espacio = key == 32;
        boolean numeros = key >= 48 && key <= 57;

        if (!(minusculas || mayusculas || espacio || numeros)) {
            evt.consume();
        }
        if (jtxtDireccion.getText().length() > 40) {
            evt.consume();
        }
    }//GEN-LAST:event_jtxtDireccionKeyTyped

    private void jtxtUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtUsuarioFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtUsuarioFocusLost

    private void jtxtUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtUsuarioKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtUsuarioKeyTyped

    private void jbtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCancelarActionPerformed
        if (this.actualizarGuardar) {
            if ((new crudController().existeUsuarioSinHuella(jtxtCedula.getText(), "usuarios"))) {
                //new crudController().eliminarUsuario(jtxtCedula.getText());
                System.out.println("Se borro");
            }
        }
        limpiarTextos();
        bloquearTextosyBusqueda();
    }//GEN-LAST:event_jbtnCancelarActionPerformed
    public boolean existeUsuario() {
        if (!this.actualizarGuardar) {
            if (!new crudController().existeUsuario(jtxtCedula.getText(), "usuarios")) {
                return true;
            } else {
                return false;
            }
        } else {
            return false;
        }
    }
    private void jbtnHuellaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnHuellaActionPerformed
        if (this.actualizarGuardar) {
            //se presiona Guardar
            if (formularioCompleto()) {
                JOptionPane.showMessageDialog(this, "Complete los datos antes de regitrar su huella dactilar");
            } else {
                if (!new crudController().existeUsuario(jtxtCedula.getText(), "estudiantes")) {
                    if (!new crudController().existeUsuario(jtxtCedula.getText(), "usuarios")) {
                        if (new crudController().existeUsuarioSinHuella(jtxtCedula.getText(), "usuarios")) {
                            int opcion = JOptionPane.showConfirmDialog(this, "Ya se ha registrado una huella.\n¿Desea registrar su huella de nuevo?", "Alerta", JOptionPane.YES_NO_OPTION);
                            if (opcion == 0) {
                                CapturaHuella capturaHuella = new CapturaHuella(jtxtCedula.getText(), true);
                                capturaHuella.setVisible(true);
                            }
                        } else {
                            CapturaHuella capturaHuella = new CapturaHuella(jtxtCedula.getText(), false);
                            capturaHuella.setVisible(true);
                        }
                    } else {
                        if (new crudController().existeUsuarioSinHuella(jtxtCedula.getText(), "usuarios")) {
                            int opcion = JOptionPane.showConfirmDialog(this, "Ya se ha registrado una huella.\n¿Desea registrar su huella de nuevo?", "Alerta", JOptionPane.YES_NO_OPTION);
                            if (opcion == 0) {
                                CapturaHuella capturaHuella = new CapturaHuella(jtxtCedula.getText(), true);
                                capturaHuella.setVisible(true);
                            }
                        } else {
                            JOptionPane.showMessageDialog(null, "EL usuario con C.I." + jtxtCedula.getText() + " ya esta registrado", "Usuario existente", JOptionPane.INFORMATION_MESSAGE);
                        }
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "EL usuario con C.I." + jtxtCedula.getText() + " esta registrado como estudiante", "Usuario existente", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        } else {
            // se presiona Actualizar
            System.out.println("editar");
            if (formularioCompleto()) {
                JOptionPane.showMessageDialog(this, "Complete los datos antes de regitrar su huella dactilar");
            } else {
                if (!new crudController().existeUsuario(jtxtCedula.getText(), "estudiantes")) {
                    int opcion = JOptionPane.showConfirmDialog(this, "Ya se ha registrado una huella.\n¿Desea registrar su huella de nuevo?", "Alerta", JOptionPane.YES_NO_OPTION);
                    if (opcion == 0) {
                        CapturaHuella capturaHuella = new CapturaHuella(jtxtCedula.getText(), true);
                        capturaHuella.setVisible(true);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "EL usuario con C.I." + jtxtCedula.getText() + " esta registrado como estudiante", "Usuario existente", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_jbtnHuellaActionPerformed

    private void jlblOcultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlblOcultarMouseClicked
        if (jlblOcultar.isEnabled()) {
            jlblVer.setVisible(true);
            jlblOcultar.setVisible(false);
            jpassClave.setEchoChar('•');
        }
    }//GEN-LAST:event_jlblOcultarMouseClicked

    private void jlblVerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlblVerMouseClicked
        if (jlblVer.isEnabled()) {
            jlblVer.setVisible(false);
            jlblOcultar.setVisible(true);
            jpassClave.setEchoChar((char) 0);
        }
    }//GEN-LAST:event_jlblVerMouseClicked

    private void jtxtCedulaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtCedulaKeyReleased
        mostrarUsuario();
    }//GEN-LAST:event_jtxtCedulaKeyReleased

    private void jtxtNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtNombreKeyReleased
        mostrarUsuario();
    }//GEN-LAST:event_jtxtNombreKeyReleased

    private void jtxtApellidoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtApellidoKeyReleased
        mostrarUsuario();
    }//GEN-LAST:event_jtxtApellidoKeyReleased

    private void jtxtBusquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtBusquedaKeyReleased
        if (jtxtBusqueda.getText().length() == 0) {
            String[] columnas = {
                "Usuario", "Cedula", "Nombre", "Apellido", "Telefono", "Direccion", "Tipo Usuario"
            };
            DefaultTableModel modeloTabla = new DefaultTableModel(null, columnas);
            jtblCrud.setModel(modeloTabla);
            if (jtxtBusqueda.getText().isEmpty()) {
                jtblCrud.setRowHeight(30);
                jtblCrud.setModel(new crudController().cargarTablaUser());
                formatoTitulos();
            }
        } else {
            jtblCrud.setModel(new crudController().buscarUsuario(jtxtBusqueda.getText()));
        }
        jtblCrud.setRowHeight(30);
        formatoTitulos();
    }//GEN-LAST:event_jtxtBusquedaKeyReleased

    public boolean formularioCompleto() {
        System.out.println(jtxtCedula.getText().isEmpty());
        System.out.println(!(jchkAdmin.isSelected() || jchkSecre.isSelected()));
        if (jtxtCedula.getText().isEmpty() || jtxtNombre.getText().isEmpty() || jtxtApellido.getText().isEmpty()
                || jtxtTelefono.getText().isEmpty() || jtxtDireccion.getText().isEmpty() || jtxtUsuario.getText().isEmpty()
                || jpassClave.getPassword().length == 0 || (!(jchkAdmin.isSelected() || jchkSecre.isSelected()))) {
            return true;
        } else {
            return false;
        }
    }

    public void mostrarUsuario() {
        if (!(jtxtCedula.getText().isEmpty()) && !(jtxtNombre.getText().isEmpty()) && !(jtxtApellido.getText().isEmpty())) {
            if (jtxtCedula.getText().length() == 10) {
                jtxtUsuario.setText(new crudController().crearUsuario(jtxtNombre.getText(), jtxtApellido.getText(), jtxtCedula.getText()));
            } else {
                jtxtUsuario.setText("");
            }
        }
    }

    public void limpiarTextos() {
        //Datos personales
        jtxtCedula.setText("");
        jtxtNombre.setText("");
        jtxtApellido.setText("");
        jtxtTelefono.setText("");
        jtxtDireccion.setText("");
        jtxtUsuario.setText("");
        jpassClave.setText("");
        jchkAdmin.setSelected(false);
        jchkSecre.setSelected(false);
    }

    public void bloquearTextosyBusqueda() {
        //Datos Personales
        jtxtCedula.setEnabled(false);
        jtxtNombre.setEnabled(false);
        jtxtApellido.setEnabled(false);
        jtxtTelefono.setEnabled(false);
        jtxtDireccion.setEnabled(false);
        jtxtUsuario.setEnabled(false);
        jpassClave.setEnabled(false);
        jchkAdmin.setEnabled(false);
        jchkSecre.setEnabled(false);
        jbtnGuardar.setEnabled(false);
        jbtnActualizar.setEnabled(false);
        jbtnHuella.setEnabled(false);
        jbtnCancelar.setEnabled(false);
        jlblVer.setEnabled(false);
        jlblOcultar.setEnabled(false);
    }

    public void bloquearTextos() {
        //Datos
        jtxtCedula.setEnabled(false);
        jtxtNombre.setEnabled(false);
        jpassClave.setEnabled(false);
        jtxtApellido.setEnabled(false);
        jchkAdmin.setEnabled(false);
    }

    public void desbloquearTextos() {
        //Datos
        jtxtCedula.setEnabled(true);
        jtxtNombre.setEnabled(true);
        jtxtApellido.setEnabled(true);
        jtxtTelefono.setEnabled(true);
        jtxtDireccion.setEnabled(true);
        jtxtUsuario.setEnabled(false);
        jpassClave.setEnabled(true);
        jchkAdmin.setEnabled(true);
        jchkSecre.setEnabled(true);
        jlblVer.setEnabled(true);
        jlblOcultar.setEnabled(true);
    }

    public void desbloquearTextosActualizar() {
        //Datos
        jtxtCedula.setEnabled(false);
        jtxtNombre.setEnabled(true);
        jtxtApellido.setEnabled(true);
        jtxtTelefono.setEnabled(true);
        jtxtDireccion.setEnabled(true);
        jpassClave.setEnabled(true);
        jlblVer.setEnabled(true);
        jlblOcultar.setEnabled(true);
        jchkAdmin.setEnabled(true);
        jchkSecre.setEnabled(true);
    }

    public boolean validadorDeCedula(String cedula) {
        boolean cedulaCorrecta = false;
        try {
            if (cedula.length() == 10) // ConstantesApp.LongitudCedula
            {
                int tercerDigito = Integer.parseInt(cedula.substring(2, 3));
                if (tercerDigito < 6) {
// Coeficientes de validación cédula
// El decimo digito se lo considera dígito verificador
                    int[] coefValCedula = {2, 1, 2, 1, 2, 1, 2, 1, 2};
                    int verificador = Integer.parseInt(cedula.substring(9, 10));
                    int suma = 0;
                    int digito = 0;
                    for (int i = 0; i < (cedula.length() - 1); i++) {
                        digito = Integer.parseInt(cedula.substring(i, i + 1)) * coefValCedula[i];
                        suma += ((digito % 10) + (digito / 10));
                    }

                    if ((suma % 10 == 0) && (suma % 10 == verificador)) {
                        cedulaCorrecta = true;
                    } else if ((10 - (suma % 10)) == verificador) {
                        cedulaCorrecta = true;
                    } else {
                        cedulaCorrecta = false;
                    }
                } else {
                    cedulaCorrecta = false;
                }
            } else {
                cedulaCorrecta = false;
            }
        } catch (NumberFormatException nfe) {
            cedulaCorrecta = false;
        } catch (Exception err) {
            //System.out.println("Una excepcion ocurrio en el proceso de validadcion");
            cedulaCorrecta = false;
        }
        return cedulaCorrecta;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnActualizar;
    private javax.swing.JButton jbtnCancelar;
    private javax.swing.JButton jbtnGuardar;
    private javax.swing.JButton jbtnHuella;
    private javax.swing.JCheckBox jchkAdmin;
    private javax.swing.JCheckBox jchkSecre;
    private javax.swing.JLabel jlApellido;
    private javax.swing.JLabel jlNombre;
    private javax.swing.JLabel jlblOcultar;
    private javax.swing.JLabel jlblVer;
    private javax.swing.JPanel jpActualizar;
    private javax.swing.JPanel jpAniadir;
    private javax.swing.JPanel jpCrud;
    private javax.swing.JPanel jpEliminar;
    private javax.swing.JPanel jpPanelOpciones;
    private javax.swing.JPasswordField jpassClave;
    private javax.swing.JTable jtblCrud;
    private javax.swing.JTextField jtxtApellido;
    private javax.swing.JTextField jtxtBusqueda;
    private javax.swing.JTextField jtxtCedula;
    private javax.swing.JTextField jtxtDireccion;
    private javax.swing.JTextField jtxtNombre;
    private javax.swing.JTextField jtxtTelefono;
    private javax.swing.JTextField jtxtUsuario;
    private javax.swing.ButtonGroup tipoUsuario;
    // End of variables declaration//GEN-END:variables
}
