/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import controladores.crudController;
import java.awt.Font;
import javax.sound.midi.ControllerEventListener;
import javax.swing.JTextField;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.JTableHeader;

/**
 *
 * @author Tefy
 */
public class crudEstudiante extends javax.swing.JPanel {

    /**
     * Creates new form crud
     */
    public crudEstudiante() {
        initComponents();
        DefaultTableModel modeloTabla = new DefaultTableModel();
        jtblCrud.setRowHeight(30);
        jtblCrud.setModel(new crudController().cargarTablaEstudiantes());
        formatoTitulos();
        this.bloquearTextosyBusqueda();
        jtblCrud.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent lse) {
                bloquearTextosyBusqueda();
                limpiarTextos();
                if (jtblCrud.getSelectedRow() != -1) {
                    Integer fila = jtblCrud.getSelectedRow();
                    jtxtCedula.setText(jtblCrud.getValueAt(fila, 0).toString());
                    jtxtNombre.setText(jtblCrud.getValueAt(fila, 1).toString());
                    jtxtApellido.setText(jtblCrud.getValueAt(fila, 2).toString());
                    jtxtTelefono.setText(jtblCrud.getValueAt(fila, 3).toString());
                    jtxtDireccion.setText(jtblCrud.getValueAt(fila, 4).toString());
                }
            }

        });
    }

    public void formatoTitulos() {
        JTableHeader th;
        th = jtblCrud.getTableHeader();
        Font fuente = new Font("Microsoft Yahei", Font.BOLD, 14);
        th.setFont(fuente);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpCrud = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jlNombre = new javax.swing.JLabel();
        jlApellido = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtxtNombre = new javax.swing.JTextField();
        jtxtApellido = new javax.swing.JTextField();
        jtxtCedula = new javax.swing.JTextField();
        jtxtDireccion = new javax.swing.JTextField();
        jbtnGuardar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jbtnActualizar = new javax.swing.JButton();
        jlNombre1 = new javax.swing.JLabel();
        jtxtTelefono = new javax.swing.JTextField();
        jbtnCancelar = new javax.swing.JButton();
        jpPanelOpciones = new javax.swing.JPanel();
        jpAniadir = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jpEliminar = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jpActualizar = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblCrud = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jtxtBusqueda = new javax.swing.JTextField();

        jpCrud.setBackground(new java.awt.Color(255, 255, 255));
        jpCrud.setPreferredSize(new java.awt.Dimension(1250, 590));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jlNombre.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jlNombre.setText("Nombre");

        jlApellido.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jlApellido.setText("Apellido");

        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jLabel3.setText("Telefono");

        jLabel4.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jLabel4.setText("Direccion");

        jtxtNombre.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 16)); // NOI18N
        jtxtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtNombreKeyTyped(evt);
            }
        });

        jtxtApellido.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 16)); // NOI18N
        jtxtApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtApellidoKeyTyped(evt);
            }
        });

        jtxtCedula.setFont(new java.awt.Font("Microsoft JhengHei", 0, 16)); // NOI18N
        jtxtCedula.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxtCedulaFocusLost(evt);
            }
        });
        jtxtCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtCedulaKeyTyped(evt);
            }
        });

        jtxtDireccion.setFont(new java.awt.Font("Microsoft JhengHei", 0, 16)); // NOI18N
        jtxtDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtDireccionKeyTyped(evt);
            }
        });

        jbtnGuardar.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 13)); // NOI18N
        jbtnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesFrames/floppy-disk.png"))); // NOI18N
        jbtnGuardar.setText("Guardar");
        jbtnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGuardarActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        jLabel6.setText("Datos Personales");

        jbtnActualizar.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 13)); // NOI18N
        jbtnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesFrames/updateUser.png"))); // NOI18N
        jbtnActualizar.setText("Actualizar");
        jbtnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnActualizarActionPerformed(evt);
            }
        });

        jlNombre1.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jlNombre1.setText("Cedula");

        jtxtTelefono.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 16)); // NOI18N
        jtxtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtTelefonoKeyTyped(evt);
            }
        });

        jbtnCancelar.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 13)); // NOI18N
        jbtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesFrames/cancel.png"))); // NOI18N
        jbtnCancelar.setText("Cancelar");
        jbtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jlApellido)
                            .addComponent(jlNombre)
                            .addComponent(jLabel3)
                            .addComponent(jlNombre1))
                        .addGap(65, 65, 65)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtTelefono)
                            .addComponent(jtxtNombre)
                            .addComponent(jtxtCedula)
                            .addComponent(jtxtDireccion)
                            .addComponent(jtxtApellido)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(101, 101, 101)
                                .addComponent(jLabel6))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(jbtnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtnActualizar))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(105, 105, 105)
                                .addComponent(jbtnCancelar)))
                        .addGap(0, 40, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jlNombre1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jlNombre))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlApellido)
                    .addComponent(jtxtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtxtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtxtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnGuardar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(198, 198, 198))
        );

        jpPanelOpciones.setBackground(new java.awt.Color(204, 204, 204));

        jpAniadir.setBackground(new java.awt.Color(204, 204, 204));
        jpAniadir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpAniadir.setPreferredSize(new java.awt.Dimension(105, 105));
        jpAniadir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpAniadirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpAniadirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpAniadirMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jpAniadirMousePressed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesFrames/agregar.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jLabel2.setText("Añadir");

        javax.swing.GroupLayout jpAniadirLayout = new javax.swing.GroupLayout(jpAniadir);
        jpAniadir.setLayout(jpAniadirLayout);
        jpAniadirLayout.setHorizontalGroup(
            jpAniadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAniadirLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jpAniadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jpAniadirLayout.setVerticalGroup(
            jpAniadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAniadirLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        jpEliminar.setBackground(new java.awt.Color(204, 204, 204));
        jpEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpEliminar.setPreferredSize(new java.awt.Dimension(105, 105));
        jpEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpEliminarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpEliminarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpEliminarMouseExited(evt);
            }
        });

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesFrames/eliminar.png"))); // NOI18N
        jLabel8.setPreferredSize(new java.awt.Dimension(105, 105));

        jLabel9.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Eliminar");

        javax.swing.GroupLayout jpEliminarLayout = new javax.swing.GroupLayout(jpEliminar);
        jpEliminar.setLayout(jpEliminarLayout);
        jpEliminarLayout.setHorizontalGroup(
            jpEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEliminarLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpEliminarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(31, 31, 31))
        );
        jpEliminarLayout.setVerticalGroup(
            jpEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEliminarLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addContainerGap())
        );

        jpActualizar.setBackground(new java.awt.Color(204, 204, 204));
        jpActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpActualizar.setPreferredSize(new java.awt.Dimension(105, 105));
        jpActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpActualizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpActualizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpActualizarMouseExited(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesFrames/hacia-adelante.png"))); // NOI18N

        jLabel11.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Actualizar");

        javax.swing.GroupLayout jpActualizarLayout = new javax.swing.GroupLayout(jpActualizar);
        jpActualizar.setLayout(jpActualizarLayout);
        jpActualizarLayout.setHorizontalGroup(
            jpActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpActualizarLayout.createSequentialGroup()
                .addGroup(jpActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpActualizarLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel11))
                    .addGroup(jpActualizarLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel10)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jpActualizarLayout.setVerticalGroup(
            jpActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpActualizarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addContainerGap())
        );

        javax.swing.GroupLayout jpPanelOpcionesLayout = new javax.swing.GroupLayout(jpPanelOpciones);
        jpPanelOpciones.setLayout(jpPanelOpcionesLayout);
        jpPanelOpcionesLayout.setHorizontalGroup(
            jpPanelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPanelOpcionesLayout.createSequentialGroup()
                .addContainerGap(232, Short.MAX_VALUE)
                .addComponent(jpAniadir, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(190, 190, 190))
        );
        jpPanelOpcionesLayout.setVerticalGroup(
            jpPanelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
            .addComponent(jpAniadir, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
            .addComponent(jpActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        jtblCrud.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        jtblCrud.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtblCrud);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 97, 830, 320));

        jLabel12.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jLabel12.setText("Buscar por cédula: ");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 38, -1, -1));

        jtxtBusqueda.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jtxtBusqueda.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxtBusquedaFocusLost(evt);
            }
        });
        jtxtBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtBusquedaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtBusquedaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtBusquedaKeyTyped(evt);
            }
        });
        jPanel4.add(jtxtBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 35, 290, -1));

        javax.swing.GroupLayout jpCrudLayout = new javax.swing.GroupLayout(jpCrud);
        jpCrud.setLayout(jpCrudLayout);
        jpCrudLayout.setHorizontalGroup(
            jpCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCrudLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jpCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jpCrudLayout.createSequentialGroup()
                        .addComponent(jpPanelOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpCrudLayout.setVerticalGroup(
            jpCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpCrudLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jpCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpCrudLayout.createSequentialGroup()
                        .addComponent(jpPanelOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(116, 116, 116))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jpCrud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jpCrud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jpAniadirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpAniadirMouseEntered
        jpAniadir.setBackground(Color.white);
    }//GEN-LAST:event_jpAniadirMouseEntered

    private void jpAniadirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpAniadirMouseExited
        jpAniadir.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_jpAniadirMouseExited

    private void jpAniadirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpAniadirMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpAniadirMousePressed

    private void jpAniadirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpAniadirMouseClicked
//              jpAniadir.setBackground(Color.white);
        this.limpiarTextos();
        this.desbloquearTextos();
        this.jbtnGuardar.setEnabled(true);
        this.jbtnCancelar.setEnabled(true);
    }//GEN-LAST:event_jpAniadirMouseClicked

    private void jpActualizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpActualizarMouseEntered
        jpActualizar.setBackground(Color.white);
    }//GEN-LAST:event_jpActualizarMouseEntered

    private void jpActualizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpActualizarMouseExited
        jpActualizar.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_jpActualizarMouseExited

    private void jbtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGuardarActionPerformed

        if (!(jtxtCedula.getText().isEmpty() || jtxtNombre.getText().isEmpty()
                || jtxtApellido.getText().isEmpty() || jtxtTelefono.getText().isEmpty() || jtxtDireccion.getText().isEmpty())) {
            if (!new crudController().existeUsuario(jtxtCedula.getText(), "usuarios")) {
                if (!new crudController().existeUsuario(jtxtCedula.getText(), "estudiantes")) {
                    new crudController().agregarEstudiante(jtxtCedula.getText(),
                            jtxtNombre.getText(),
                            jtxtApellido.getText(),
                            jtxtTelefono.getText(),
                            jtxtDireccion.getText());

                    this.limpiarTextos();
                    this.bloquearTextosyBusqueda();
                } else {
                    JOptionPane.showMessageDialog(null, "El usuario ya existe");
                }
            }else{
                JOptionPane.showMessageDialog(this, "El estudiante ya se encuentra registrado como secretario/a o administrador/a.");
            }
            jtblCrud.setModel(new crudController().cargarTablaEstudiantes());
        } else {
            JOptionPane.showMessageDialog(this, "Complete todos los campos antes de guardar");
        }

    }//GEN-LAST:event_jbtnGuardarActionPerformed

    private void jpActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpActualizarMouseClicked
        if (jtxtCedula.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Primero seleccione una fila de la tabla");
        } else {
            this.desbloquearTextosActualizar();

            this.jbtnGuardar.setEnabled(false);
            jbtnActualizar.setEnabled(true);
            jbtnCancelar.setEnabled(true);
        }

    }//GEN-LAST:event_jpActualizarMouseClicked

    private void jtxtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtNombreKeyTyped
        int key = evt.getKeyChar();

        boolean mayusculas = key >= 65 && key <= 90;
        boolean minusculas = key >= 97 && key <= 122;
        boolean espacio = key == 32;

        if (!(minusculas || mayusculas || espacio)) {
            evt.consume();
        }
        if (jtxtNombre.getText().length() > 40) {
            evt.consume();
        }
    }//GEN-LAST:event_jtxtNombreKeyTyped

    private void jtxtApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtApellidoKeyTyped
        int key = evt.getKeyChar();

        boolean mayusculas = key >= 65 && key <= 90;
        boolean minusculas = key >= 97 && key <= 122;
        boolean espacio = key == 32;

        if (!(minusculas || mayusculas || espacio)) {
            evt.consume();
        }
        if (jtxtApellido.getText().length() > 40) {
            evt.consume();
        }
    }//GEN-LAST:event_jtxtApellidoKeyTyped

    private void jtxtCedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtCedulaKeyTyped
        int key = evt.getKeyChar();

        boolean numeros = key >= 48 && key <= 57;

        if (!numeros) {
            evt.consume();
        }
        if (jtxtCedula.getText().length() >= 10) {
            evt.consume();
        }
    }//GEN-LAST:event_jtxtCedulaKeyTyped

    private void jtxtBusquedaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtBusquedaKeyTyped
        int key = evt.getKeyChar();

        boolean numeros = key >= 48 && key <= 57;

        if (!numeros) {
            evt.consume();
        }
        if (jtxtBusqueda.getText().length() >= 10) {
            evt.consume();
        }

    }//GEN-LAST:event_jtxtBusquedaKeyTyped

    private void jtxtBusquedaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtBusquedaFocusLost

    }//GEN-LAST:event_jtxtBusquedaFocusLost

    private void jtxtCedulaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtCedulaFocusLost
        if (!this.validadorDeCedula(jtxtCedula.getText())) {
            jtxtCedula.setText("");
        }

    }//GEN-LAST:event_jtxtCedulaFocusLost

    private void jbtnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnActualizarActionPerformed
        new crudController().updateEstudiante(jtxtCedula.getText(), jtxtNombre.getText(), jtxtApellido.getText(), jtxtTelefono.getText(), jtxtDireccion.getText());
        jtblCrud.setModel(new crudController().cargarTablaEstudiantes());
        this.bloquearTextosyBusqueda();
    }//GEN-LAST:event_jbtnActualizarActionPerformed

    private void jpEliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpEliminarMouseExited
        jpEliminar.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_jpEliminarMouseExited

    private void jpEliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpEliminarMouseEntered
        jpEliminar.setBackground(Color.white);
    }//GEN-LAST:event_jpEliminarMouseEntered

    private void jpEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpEliminarMouseClicked
        if (jtxtCedula.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Primero seleccione una fila de la tabla");
        } else {
            String mensaje = String.format("%s\n\n%15s%-20s\n%15s%s %s\n%15s%-20s\n%15s%-20s",
                    "¿Esta seguro de eliminar estudiante?", "Cedula: ", jtxtCedula.getText(),
                    "Estudiante: ", jtxtNombre.getText(), jtxtApellido.getText(),
                    "Telefono: ", jtxtTelefono.getText(),
                    "Direccion: ", jtxtDireccion.getText());
            int opcion = JOptionPane.showConfirmDialog(this, mensaje, "Eliminar Estudiate", JOptionPane.WARNING_MESSAGE, JOptionPane.YES_NO_OPTION);
            if (opcion == 0) {
                new crudController().eliminarEstudiante(jtxtCedula.getText());
            }
            jtblCrud.setModel(new crudController().cargarTablaEstudiantes());
        }
    }//GEN-LAST:event_jpEliminarMouseClicked

    private void jtxtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtTelefonoKeyTyped
        int key = evt.getKeyChar();

        boolean numeros = key >= 48 && key <= 57;

        if (!numeros) {
            evt.consume();
        }
        if (jtxtTelefono.getText().length() >= 10) {
            evt.consume();
        }
        if (jtxtTelefono.getText().length() >= 10) {
            evt.consume();
        }
    }//GEN-LAST:event_jtxtTelefonoKeyTyped

    private void jtxtBusquedaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtBusquedaKeyPressed

    }//GEN-LAST:event_jtxtBusquedaKeyPressed

    private void jbtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCancelarActionPerformed
        bloquearTextosyBusqueda();
        limpiarTextos();
    }//GEN-LAST:event_jbtnCancelarActionPerformed

    private void jtxtDireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtDireccionKeyTyped
        int key = evt.getKeyChar();

        boolean mayusculas = key >= 65 && key <= 90;
        boolean minusculas = key >= 97 && key <= 122;
        boolean espacio = key == 32;
        boolean numeros = key >= 48 && key <= 57;

        if (!(minusculas || mayusculas || espacio || numeros)) {
            evt.consume();
        }
        if (jtxtDireccion.getText().length() > 40) {
            evt.consume();
        }
    }//GEN-LAST:event_jtxtDireccionKeyTyped

    private void jtxtBusquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtBusquedaKeyReleased
        if (jtxtBusqueda.getText().length() == 0) {
            //JOptionPane.showMessageDialog(null, "No existe un usuario con la cédula especificada");
            String[] columnas = {
                "Cedula", "Nombre", "Apellido", "Telefono", "Direccion"
            };
            DefaultTableModel modeloTabla = new DefaultTableModel(null, columnas);
            jtblCrud.setModel(modeloTabla);
            if (jtxtBusqueda.getText().isEmpty()) {
                jtblCrud.setRowHeight(30);
                jtblCrud.setModel(new crudController().cargarTablaEstudiantes());
                formatoTitulos();
            }
        } else {
            jtblCrud.setModel(new crudController().buscarEstudiante(jtxtBusqueda.getText()));
        }
        jtblCrud.setRowHeight(30);
        formatoTitulos();
    }//GEN-LAST:event_jtxtBusquedaKeyReleased

    public void limpiarTextos() {
        //Datos personales
        jtxtCedula.setText("");
        jtxtNombre.setText("");
        jtxtApellido.setText("");
        jtxtTelefono.setText("");
        jtxtDireccion.setText("");
    }

    public void bloquearTextosyBusqueda() {
        //Datos Personales
        jtxtCedula.setEnabled(false);
        jtxtNombre.setEnabled(false);
        jtxtDireccion.setEnabled(false);
        jtxtApellido.setEnabled(false);
        jtxtTelefono.setEnabled(false);
        jbtnGuardar.setEnabled(false);
        jbtnActualizar.setEnabled(false);
        jbtnCancelar.setEnabled(false);
    }

    public void bloquearTextos() {
        //Datos
        jtxtCedula.setEnabled(false);
        jtxtNombre.setEnabled(false);
        jtxtDireccion.setEnabled(false);
        jtxtApellido.setEnabled(false);
        jtxtTelefono.setEnabled(false);
    }

    public void desbloquearTextos() {
        //Datos
        jtxtCedula.setEnabled(true);
        jtxtNombre.setEnabled(true);
        jtxtDireccion.setEnabled(true);
        jtxtApellido.setEnabled(true);
        jtxtTelefono.setEnabled(true);
    }

    public void desbloquearTextosActualizar() {
        //Datos
        jtxtCedula.setEnabled(false);
        jtxtNombre.setEnabled(true);
        jtxtDireccion.setEnabled(true);
        jtxtApellido.setEnabled(true);
        jtxtTelefono.setEnabled(true);
    }

    public boolean validadorDeCedula(String cedula) {
        boolean cedulaCorrecta = false;

        try {

            if (cedula.length() == 10) // ConstantesApp.LongitudCedula
            {
                int tercerDigito = Integer.parseInt(cedula.substring(2, 3));
                if (tercerDigito < 6) {
// Coeficientes de validación cédula
// El decimo digito se lo considera dígito verificador
                    int[] coefValCedula = {2, 1, 2, 1, 2, 1, 2, 1, 2};
                    int verificador = Integer.parseInt(cedula.substring(9, 10));
                    int suma = 0;
                    int digito = 0;
                    for (int i = 0; i < (cedula.length() - 1); i++) {
                        digito = Integer.parseInt(cedula.substring(i, i + 1)) * coefValCedula[i];
                        suma += ((digito % 10) + (digito / 10));
                    }

                    if ((suma % 10 == 0) && (suma % 10 == verificador)) {
                        cedulaCorrecta = true;
                    } else if ((10 - (suma % 10)) == verificador) {
                        cedulaCorrecta = true;
                    } else {
                        cedulaCorrecta = false;
                    }
                } else {
                    cedulaCorrecta = false;
                }
            } else {
                cedulaCorrecta = false;
            }
        } catch (NumberFormatException nfe) {
            cedulaCorrecta = false;
        } catch (Exception err) {
            //System.out.println("Una excepcion ocurrio en el proceso de validadcion");
            cedulaCorrecta = false;
        }

        if (!cedulaCorrecta) {
            JOptionPane.showMessageDialog(null, "La cédula ingresada no es válida");

        }
        return cedulaCorrecta;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnActualizar;
    private javax.swing.JButton jbtnCancelar;
    private javax.swing.JButton jbtnGuardar;
    private javax.swing.JLabel jlApellido;
    private javax.swing.JLabel jlNombre;
    private javax.swing.JLabel jlNombre1;
    private javax.swing.JPanel jpActualizar;
    private javax.swing.JPanel jpAniadir;
    private javax.swing.JPanel jpCrud;
    private javax.swing.JPanel jpEliminar;
    private javax.swing.JPanel jpPanelOpciones;
    private javax.swing.JTable jtblCrud;
    private javax.swing.JTextField jtxtApellido;
    private javax.swing.JTextField jtxtBusqueda;
    private javax.swing.JTextField jtxtCedula;
    private javax.swing.JTextField jtxtDireccion;
    private javax.swing.JTextField jtxtNombre;
    private javax.swing.JTextField jtxtTelefono;
    // End of variables declaration//GEN-END:variables
}
